server:
  port: 8082

spring:
  config:
    import:
      - classpath:application-shared.yml
      - classpath:application-pub-sub.yml

  application:
    name: audit-service

logging:
  level:
    io.github.Hyeonqz: DEBUG
